### ISSUE TITLE
微博登录报错了

### ISSUE THREAD

**Issue by leahoop** [LoseNine/Crack-JS-Spider#3]
`Traceback (most recent call last):
  File "E:/python/Crack-JS-Spider/微博/weibo.py", line 132, in <module>
    weibo.main()
  File "E:/python/Crack-JS-Spider/微博/weibo.py", line 125, in main
    self.login()
  File "E:/python/Crack-JS-Spider/微博/weibo.py", line 111, in login
    ticket, ssosavestate = re.findall(r'ticket=(.*?)&ssosavestate=(.*?)"', result)[0]  # 获取ticket和ssosavestate参数
IndexError: list index out of range`

**Comment by wangjuham** [comment]
我也是出现这个问题，估计是微博那边改了
